package pojos;
// Generated Feb 11, 2019 8:37:09 PM by Hibernate Tools 4.3.1



/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private String customerKey;
     private String lastName;
     private String firstName;
     private String phone;
     private String street1;
     private String street2;
     private String city;
     private String state;
     private String zipCode;

    public Customer() {
    }

	
    public Customer(String customerKey, String lastName, String firstName, String phone) {
        this.customerKey = customerKey;
        this.lastName = lastName;
        this.firstName = firstName;
        this.phone = phone;
    }
    public Customer(String customerKey, String lastName, String firstName, String phone, String street1, String street2, String city, String state, String zipCode) {
       this.customerKey = customerKey;
       this.lastName = lastName;
       this.firstName = firstName;
       this.phone = phone;
       this.street1 = street1;
       this.street2 = street2;
       this.city = city;
       this.state = state;
       this.zipCode = zipCode;
    }
   
    public String getCustomerKey() {
        return this.customerKey;
    }
    
    public void setCustomerKey(String customerKey) {
        this.customerKey = customerKey;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getStreet1() {
        return this.street1;
    }
    
    public void setStreet1(String street1) {
        this.street1 = street1;
    }
    public String getStreet2() {
        return this.street2;
    }
    
    public void setStreet2(String street2) {
        this.street2 = street2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }




}


